# Generated by Django 4.2.5 on 2023-09-10 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_f', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AbstractUser',
            fields=[
                ('basicmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='EvenPyApp.basicmodel')),
                ('username_f', models.CharField(max_length=100)),
                ('email_f', models.CharField(max_length=100)),
                ('password_f', models.CharField(max_length=20)),
            ],
            bases=('EvenPyApp.basicmodel',),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('basicmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='EvenPyApp.basicmodel')),
            ],
            bases=('EvenPyApp.basicmodel',),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('abstractuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='EvenPyApp.abstractuser')),
            ],
            bases=('EvenPyApp.abstractuser',),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('participant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='EvenPyApp.participant')),
            ],
            bases=('EvenPyApp.participant',),
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('participant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='EvenPyApp.participant')),
            ],
            bases=('EvenPyApp.participant',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('basicmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='EvenPyApp.basicmodel')),
                ('start_date_f', models.DateTimeField()),
                ('end_date_f', models.DateTimeField()),
                ('organizer_f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EvenPyApp.organizer')),
            ],
            bases=('EvenPyApp.basicmodel',),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('basicmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='EvenPyApp.basicmodel')),
                ('start_hour_f', models.DateTimeField()),
                ('end_hour_f', models.DateTimeField()),
                ('event_f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='EvenPyApp.event')),
                ('location_f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='EvenPyApp.location')),
                ('participants_f', models.ManyToManyField(blank=True, related_name='participant', to='EvenPyApp.participant')),
                ('instructor_f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='EvenPyApp.instructor')),
            ],
            bases=('EvenPyApp.basicmodel',),
        ),
    ]
