# Generated by Django 4.2.5 on 2023-09-11 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_f', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_f', models.CharField(max_length=100)),
                ('email_f', models.CharField(max_length=100, unique=True)),
                ('password_f', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='EvenPyApp.user')),
            ],
            options={
                'abstract': False,
            },
            bases=('EvenPyApp.user',),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('participant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='EvenPyApp.participant')),
            ],
            options={
                'abstract': False,
            },
            bases=('EvenPyApp.participant',),
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('participant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='EvenPyApp.participant')),
            ],
            options={
                'abstract': False,
            },
            bases=('EvenPyApp.participant',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_f', models.CharField(max_length=100)),
                ('start_date_f', models.DateTimeField()),
                ('end_date_f', models.DateTimeField()),
                ('organizer_f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EvenPyApp.organizer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_f', models.CharField(max_length=100)),
                ('start_hour_f', models.DateTimeField()),
                ('end_hour_f', models.DateTimeField()),
                ('event_f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='EvenPyApp.event')),
                ('location_f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='EvenPyApp.location')),
                ('participants_f', models.ManyToManyField(blank=True, related_name='participant', to='EvenPyApp.participant')),
                ('instructor_f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='EvenPyApp.instructor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
