# Generated by Django 4.2.5 on 2023-10-03 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='conductor',
        ),
    ]
